[package]
name = "rly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.23.0", features = ["full"] }
clap = { version  = "4.0.32", features = ["derive", "wrap_help"] }
anyhow = "1.0.68"
serde = { version = "1.0.152" }
serde_derive = "1.0.152"
pretty_assertions = "1.3.0"
chrono = "0.4.23"

log = "0.4.17"
pretty_env_logger = "0.4.0"